### ISSUE TITLE
Crash on showing "GPS not available" dialog

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#16]
Acra-Report-ID: a0a178a7-7dc4-4c30-b19b-123818417baf

```
com.afollestad.materialdialogs.MaterialDialog$DialogException: Bad window token, you cannot show a dialog before an Activity is created or after it's hidden.
    at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1119)
    at org.berlin_vegan.bvapp.UiUtils.showMaterialDialog(UiUtils.java:60)
    at org.berlin_vegan.bvapp.UiUtils.showMaterialDialog(UiUtils.java:26)
    at org.berlin_vegan.bvapp.MainListActivity$5.run(MainListActivity.java:266)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5940)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)

```

**Comment by jmastr** [comment]
Die Exception verdeckt wahrscheinlich eine andere Exception, wie hier der erste Kommentar beschreibt: http://stackoverflow.com/questions/2850573/activity-has-leaked-window-that-was-originally-added?answertab=votes#tab-top

**Comment by IncorporateApps** [comment]
Es hat zu lange gedauert und er hat schon auf zurück geklickt, danach kam aber der Async mit dem "Zeig ein Dialog" Befehl.

Am besten man guckt im Async ob getApplicationContext() !=null oder getActivity()!=null oder beides bevor man MaterialDialog.show aufruft.

**Comment by IncorporateApps** [comment]
bisschen doppelt gemoppelt - man könnte ja auch zusätzlich im MaterialDialog.show auch ein try catch einbauen. Sicher ist sicher

**Comment by jmastr** [comment]
Du scheinst das zu kennen und wissen, was zu tun ist. Kannst du den Patch machen?

**Comment by IncorporateApps** [comment]
Momentan leider null Zeit ich arbeite an 3 andere Sachen gleichzeitig.
