### ISSUE TITLE
Crash (Nullpointer) beim Hinzufügen von Favoriten

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#18]
Acra-Report-ID: feb56701-8365-4e22-8af9-37429b8e1755
Acra-Report-ID: 93f3ff93-4528-4349-9e4b-028018c56c90

```
java.lang.NullPointerException
    at org.berlin_vegan.bvapp.GastroLocations.commitFavoritesPreferences(GastroLocations.java:118)
    at org.berlin_vegan.bvapp.GastroLocations.addFavorite(GastroLocations.java:109)
    at org.berlin_vegan.bvapp.GastroActivity.onOptionsItemSelected(GastroActivity.java:72)
    at android.app.Activity.onMenuItemSelected(Activity.java:2548)
    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:353)
    at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
    at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
    at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
    at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:74)
    at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:164)
    at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:740)
    at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
    at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
    at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
    at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
    at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:598)
    at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
    at android.view.View.performClick(View.java:4278)
    at android.view.View$PerformClick.run(View.java:17429)
    at android.os.Handler.handleCallback(Handler.java:725)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5099)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:803)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:570)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by jmastr** [comment]
Mir fällt gerade auf, dass mir bei ACRA der Grund für den Crash fehlt, z.B. in der ersten Zeile so etwas wie: 'java.lang.NullPointerException: Attempt to invoke interface method 'android.content.SharedPreferences$Editor android.content.SharedPreferences.edit()' on a null object reference'. Kann man das irgendwie noch einstellen?

Ich kann mir nämlich nicht erklären wie `sSharedPreferences` an der Stelle `null` sein soll. Ist aber das einzige, was in der Zeile: `SharedPreferences.Editor editor = sSharedPreferences.edit();` zur NPE führen kann, oder? Würde dann einfach eine `null`-Abfrage einbauen, auch wenn ich den Fehler nicht nachstellen kann.

Btw.: Auf meinem Gerät lande ich übrigens dann wieder in der MainListActivity. Ist also von der User Experience nicht sooo schlimm...

**Comment by smeir** [comment]
Hmm, gute Frage. Wüsste auch nicht wie man den genauen Grund noch sehen kann. 

Wegen dem `sSharedPreferences` könnte ich mir schon vorstellen wie das passiert. Die `sSharedPreferences` wird ja nur initialisiert, wenn vorher eine `MainListActivity` erstellt wurde. Wenn man jetzt in der GastroActivity ist, könnte es passieren das Android die `MainListActivity` killt und somit in `GastroLocations` die ganzen `mMainListActivity` auf `null` gehen. Jede Activity kann ja jederzeit gekillt werden. Ich befürchte da schlummert noch einiges an Nullpointern. :-( Ich glaube die einzige Instanz die relativ stabil ist, ist die Application Instanz. Diese bleibt immer erhalten, soweit ich weiss. Die Activities selbst können sich nicht darauf verlassen, das eine andere Activity noch da ist. Ein anderes Szenario wäre auch, wenn der Benutzer in der `GastroActivity` ist, dann auf Home drückt und am nächsten Tag die App wieder öffnet. Dann landet er direkt in der `GastroActivity`und ich befürchte die `MainListActivity` ist dann nicht mehr vorhanden.

**Comment by jmastr** [comment]
Da gebe ich dir recht. Da könnte noch so einiges schlummern. Gibt es da
best practice guide lines? Werde mal versuchen mit dem einen Szenario eine
Exception zu erzeugen...

**Comment by smeir** [comment]
Ich habe es mal provoziert. Siehe aktuellen Crash-Report.
- unter Entwickler-Optionen eingestellt, das Activities immer gekillt werden, wenn sie nicht sichtbar sind. Bei mir heisst das "Don't keep activities"
- MainlistActivity->GastroActivity
- dann Adresse ausgewählt -> Google Maps
- dann "back" und dann Favorite angeklickt.

**Comment by jmastr** [comment]
Ich kann leider mit der CyanogenMod Version, die ich verwende, das mit
deiner Anleitung nicht nach stellen...

@Georgi: Hast du da best practice Tipps? Ich habe gelesen, man könne
getApplicationContext() verwenden ohne immer die MainListActivity rum zu
reichen...

**Comment by IncorporateApps** [comment]
Ich guck mir morgen alle Bugs vor dem Treffen an

**Comment by IncorporateApps** [comment]
Wurde das behoben? Konnte ich nach Sandy's Anleitung nicht provozieren.

**Comment by IncorporateApps** [comment]
Ah ok, nicht Back sondern Home muss man drücken,  bei back gibt es keinen Crash

**Comment by IncorporateApps** [comment]
Hat mit dem close des Tickets nicht wirklich funktioniert, der Commit sieht aber gut aus
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by jmastr** [comment]
Du musst 'Closed #18' in die git commit message schreiben. Gibt auch
Anleitungen auf github dazu...

**Comment by IncorporateApps** [comment]
Habe ich auch genau die Anleitung verlinkt.

The following keywords will close an issue via commit message:

close
closes
closed
fix
fixes
fixed
resolve
resolves
resolved

Hat trotzdem nicht funktioniert

**Comment by jmastr** [comment]
Besser sogar 'Closes #18' oder 'Fixes #18'. Am besten als letzten Satz.
Guck mal in die git history. Ich habe das schon irgendwo gemacht

**Comment by IncorporateApps** [comment]
Laut Anleitung ist mein Syntax ok:
For example, "This closes #34, closes #23"
und bei mir "fixes #18, fixes #16 "

**Comment by jmastr** [comment]
Wieso ist der Issue schon zu? Das sollte eigentlich nur passieren, wenn wir auf master gemerged und somit released haben. Wird irgendwann unübersichtlich. So geht's:

https://github.com/Berlin-Vegan/berlin-vegan-guide/commit/4d4367c83e115997d1888cb2dbf6dd0b9b602089

**Comment by IncorporateApps** [comment]
Und wie willst du dann die Bugs im Dev als closed markieren, damit die nicht in der open Liste auftauchen?

**Comment by jmastr** [comment]
Das ist halt nicht der github-workflow. Guck dir mal https://github.com/Berlin-Vegan/berlin-vegan-guide/issues/13 an. Da wurde automatisch ein Kommentar erzeugt, als ich auf development gepushed habe und das Ticket automatisch geschlossen, als ich auf master gepushed hatte.

Ich denke, wir sollten den workflow so leben, wie er von github vorgegeben ist.

**Comment by smeir** [comment]
Ah, ok. Dann habe ich es bisher auch falsch gemacht.
