### ISSUE TITLE
Crash on GastroLocationViewHolder#onClick (ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#21]
acra-report-id: 19884aad-2250-4f79-9a7e-e68ac8124898

```
java.lang.ArrayIndexOutOfBoundsException: length=271; index=-1
    at java.util.ArrayList.get(ArrayList.java:306)
    at org.berlin_vegan.bvapp.data.GastroLocations.get(GastroLocations.java:203)
    at org.berlin_vegan.bvapp.adapters.GastroLocationAdapter$GastroLocationViewHolder.onClick(GastroLocationAdapter.java:87)
    at android.view.View.performClick(View.java:4293)
    at android.view.ViewRootImpl.performClickHelper(ViewRootImpl.java:922)
    at android.view.ViewRootImpl.performClick(ViewRootImpl.java:931)
    at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3123)
    at android.os.Handler.dispatchMessage(Handler.java:119)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4873)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:528)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by smeir** [comment]
So wie ich die Doku zu `getAdapterPosition()` verstehe kann es Probleme geben wenn wir vorher ein `notifyDataSetChanged()`  aufrufen und dann Android noch nicht das Layout neu berechnet hat. Dann kommt ein -1 zurück. Stabiler scheint das `getLayoutPosition()` zu sein.
