### ISSUE TITLE
Crash:  No Activity found to handle Intent

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#37]
acra: 6221d6c0-b60c-4270-b36a-f4699b4181e3

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.google.android.gms flg=0x80000 pkg=com.android.vending }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1559)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1418)
    at android.app.Activity.startActivityForResult(Activity.java:3351)
    at android.app.Activity.startActivityForResult(Activity.java:3312)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:820)
    at android.app.Activity.startActivity(Activity.java:3522)
    at android.app.Activity.startActivity(Activity.java:3490)
    at com.google.android.gms.dynamic.zza$5.onClick(Unknown Source)
    at android.view.View.performClick(View.java:4084)
    at android.view.ViewDebug$3.run(ViewDebug.java:914)
    at android.os.Handler.handleCallback(Handler.java:630)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4754)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
    at dalvik.system.NativeStart.main(Native Method)

```

**Comment by smeir** [comment]
seems that user has installed playstore apk, but not play services

solution? https://code.google.com/p/android/issues/detail?id=42543

**Comment by smeir** [comment]
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.google.android.gms&pcampaignid=gcore_8115000--- flg=0x80000 pkg=com.android.vending }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1657)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
    at android.app.Activity.startActivityForResult(Activity.java:3456)
    at android.app.Activity.startActivityForResult(Activity.java:3417)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:784)
    at android.app.Activity.startActivity(Activity.java:3653)
    at android.app.Activity.startActivity(Activity.java:3621)
    at com.google.android.gms.dynamic.zza$5.onClick(Unknown Source)
    at android.view.View.performClick(View.java:4240)
    at android.view.View$PerformClick.run(View.java:17742)
    at android.os.Handler.handleCallback(Handler.java:730)
    at android.os.Handler.dispatchMessage(Handler.java:92)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:5121)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:525)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
    at dalvik.system.NativeStart.main(Native Method)
```
