### ISSUE TITLE
Crash: java.lang.IllegalArgumentException: no providers found for criteria

### ISSUE THREAD

**Issue by smeir** [Berlin-Vegan/berlin-vegan-guide#39]
acra: 08825400-3ea6-46d5-88f9-ab7f31597ff4

```
java.lang.RuntimeException: Unable to resume activity {org.berlin_vegan.bvapp_alpha/org.berlin_vegan.bvapp.activities.MainListActivity}: java.lang.IllegalArgumentException: no providers found for criteria
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2639)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2667)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2140)
    at android.app.ActivityThread.access$700(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4921)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: no providers found for criteria
    at android.os.Parcel.readException(Parcel.java:1429)
    at android.os.Parcel.readException(Parcel.java:1379)
    at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:659)
    at android.location.LocationManager._requestLocationUpdates(LocationManager.java:664)
    at android.location.LocationManager.requestSingleUpdate(LocationManager.java:925)
    at org.berlin_vegan.bvapp.activities.MainListActivity.requestLocationUpdates(MainListActivity.java:265)
    at org.berlin_vegan.bvapp.activities.MainListActivity.onResume(MainListActivity.java:112)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1199)
    at android.app.Activity.performResume(Activity.java:5280)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2629)
    ... 12 more
java.lang.IllegalArgumentException: no providers found for criteria
    at android.os.Parcel.readException(Parcel.java:1429)
    at android.os.Parcel.readException(Parcel.java:1379)
    at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:659)
    at android.location.LocationManager._requestLocationUpdates(LocationManager.java:664)
    at android.location.LocationManager.requestSingleUpdate(LocationManager.java:925)
    at org.berlin_vegan.bvapp.activities.MainListActivity.requestLocationUpdates(MainListActivity.java:265)
    at org.berlin_vegan.bvapp.activities.MainListActivity.onResume(MainListActivity.java:112)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1199)
    at android.app.Activity.performResume(Activity.java:5280)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2629)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2667)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2140)
    at android.app.ActivityThread.access$700(ActivityThread.java:140)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4921)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ces92** [comment]
Ist der weg?

**Comment by smeir** [comment]
Nein, der erscheint leider noch, ist aber relativ selten. Ich schaue mal morgen, ob ich die Ursache finde, wenn nicht schieben wir das auf die nächste Version. Wahrscheinlich sind alle Location Dienste komplett abgeschaltet.

**Comment by smeir** [comment]
Mitlerweile tritt das Problem häufiger auf, sollten wir fixen

**Comment by ces92** [comment]
Würde das mit einem simplen try catch abfangen und einen Toast ausgeben.

**Comment by smeir** [comment]
Ich denke mal wir machen da einen Fehler und müssen in dem Fall irgendwelche andere Provider verwenden. Bisher auf Samsung und HTC smartphones gesehen, immer mit Android 4.1.x

**Comment by smeir** [comment]
Ist gefixt. Scheinbar war kein Provider für GPS verfügbar. Jetzt erscheint eine Fehlermeldung.
